### ISSUE TITLE
pipeline_inference

### ISSUE THREAD

**Issue by Cloud-Rambler** [THUNLP-MT/dyMEAN#13]
Great work! Can you provide the code used in this file？Thank you！
<img width="690" alt="图片" src="https://github.com/THUNLP-MT/dyMEAN/assets/69468968/ce5b3b20-0413-4eff-be69-f0a0e1fb8f72">

**Comment by kxz18** [comment]
Hi, they are under the folder ["models"](https://github.com/THUNLP-MT/dyMEAN/tree/main/models/pipeline). The paths in the script are wrong and I've just corrected them.

**Comment by Cloud-Rambler** [comment]
Thanks
