### ISSUE TITLE
Hdock receptor and ligand

### ISSUE THREAD

**Issue by kdnghw** [THUNLP-MT/dyMEAN#26]
Hello!

I am very interested in your research and have some questions that I hope you can guide me on. In your study, regarding the part about Hdock docking, how do you define the receptor and ligand in the Hdock docking process? Are the receptor and ligand the antigen or the antibody? Thank you very much for taking the time to answer these questions. Your insights and experience are of great significance to our research work. Looking forward to your reply!

Best regards!

**Comment by kxz18** [comment]
Hi, thanks for your interest in our work! The usage of hdock can be found here: https://github.com/THUNLP-MT/dyMEAN/blob/main/models/pipeline/hdock_api.py. The receptor is the antigen and the ligand is the antibody.

**Comment by kdnghw** [comment]
Thank you very much for your prompt and informative response. I appreciate your clarification regarding the roles of the receptor and ligand in the Hdock docking process.

However, in my previous readings of papers or materials related to Hdock, I was unable to find explicit definitions, which leads me to inquire about the basis for this delineation. Could you please elaborate on the criteria or principles that guide the classification of the receptor as the antigen and the ligand as the antibody in your research? Understanding the rationale behind this distinction would greatly enhance my comprehension of the docking process and its applications.

Thank you once again for your time and guidance. I am looking forward to your further insights.

**Comment by kxz18** [comment]
I think this might be a convention in drug discovery. Usually we regard the target protein as the receptor, and the drug as the ligand. Another project on antibody design also adopts this convention: https://github.com/luost26/diffab/blob/main/diffab/tools/dock/hdock.py.

**Comment by kdnghw** [comment]
Thank you for providing this insightful explanation and for sharing the additional resource. It's very helpful for my understanding and research.
